[build]
  command = 'yarn build && yarn build:lambda'
  publish = 'dist'
  functions = '.functions'

[[redirects]]
  from='/unshortener/:shortenedUrl'
  to='/.netlify/functions/unshortener?shortenedUrl=:shortenedUrl'
