[build]
  command = "yarn build && yarn build:lambda"
  publish = "dist"
  functions = ".functions"

[[redirects]]
  from="/unshortener/*"
  to="/.netlify/functions/unshortener?shortenedUrl=:splat"
  force = true
