[build]
  command = 'yarn build && yarn build:lambda'
  publish = 'dist'
  functions = '.functions'

# https://www.netlify.com/docs/redirects/
# https://www.netlify.com/docs/netlify-toml-reference/

[[redirects]]
  from="/unshortener/:shortenedUrl"
  to="/.netlify/functions/unshortener?shortenedUrl=:shortenedUrl"